# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 389)
        MainWindow.setMinimumSize(QtCore.QSize(520, 389))
        MainWindow.setMaximumSize(QtCore.QSize(520, 389))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Flag = QtWidgets.QLabel(self.centralwidget)
        self.Flag.setGeometry(QtCore.QRect(0, 0, 140, 90))
        self.Flag.setMinimumSize(QtCore.QSize(140, 90))
        self.Flag.setText("")
        self.Flag.setObjectName("Flag")
        self.OutputWindow = QtWidgets.QLabel(self.centralwidget)
        self.OutputWindow.setGeometry(QtCore.QRect(70, 130, 371, 41))
        self.OutputWindow.setAlignment(QtCore.Qt.AlignCenter)
        self.OutputWindow.setObjectName("OutputWindow")
        self.ToExecute = QtWidgets.QPushButton(self.centralwidget)
        self.ToExecute.setGeometry(QtCore.QRect(213, 270, 101, 31))
        self.ToExecute.setObjectName("ToExecute")
        self.Input = QtWidgets.QLineEdit(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(173, 210, 181, 31))
        self.Input.setObjectName("Input")
        self.ToHistoryOfRequests = QtWidgets.QPushButton(self.centralwidget)
        self.ToHistoryOfRequests.setGeometry(QtCore.QRect(360, 312, 161, 31))
        self.ToHistoryOfRequests.setObjectName("ToHistoryOfRequests")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 90, 331, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Country = QtWidgets.QLabel(self.layoutWidget)
        self.Country.setText("")
        self.Country.setObjectName("Country")
        self.verticalLayout.addWidget(self.Country)
        self.SubjetOFtheCountry = QtWidgets.QLabel(self.layoutWidget)
        self.SubjetOFtheCountry.setText("")
        self.SubjetOFtheCountry.setObjectName("SubjetOFtheCountry")
        self.verticalLayout.addWidget(self.SubjetOFtheCountry)
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(60, 200, 111, 51))
        self.text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_label.setWordWrap(False)
        self.text_label.setObjectName("text_label")
        self.to_settings_btn = QtWidgets.QPushButton(self.centralwidget)
        self.to_settings_btn.setGeometry(QtCore.QRect(480, 10, 31, 31))
        self.to_settings_btn.setText("")
        self.to_settings_btn.setObjectName("to_settings_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Local time calculator"))
        self.OutputWindow.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ToExecute.setText(_translate("MainWindow", "Execute"))
        self.ToHistoryOfRequests.setText(_translate("MainWindow", "Go to the history of requests"))
        self.text_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Input the name </span></p><p align=\"center\"><span style=\" font-size:10pt;\">of the city/town</span></p></body></html>"))
